### ISSUE TITLE
bug Can't write a comment under videos /-:

### ISSUE THREAD

**Issue by YAROMiRas** [sheddup/YoutubeAUDIO#11]
Physical field for new comment missing when extension enabled...

**Comment by sheddup** [comment]
Weird bug, looking at it now.

EDIT: fixed in 1.5.7, #header selector in inject.css was hiding the comment field https://github.com/sheddup/YoutubeAUDIO/blob/56faafc6a2147cf80ec2dc5064a69e27f7fc2898/scripts/content_scripts/inject.css#L5
