### ISSUE TITLE
Work per tab

### ISSUE THREAD

**Issue by Madis0** [sheddup/YoutubeAUDIO#4]
I found this extension today and it seems to work well so far. 

I was thinking though, perhaps you could add an usability feature to limit the behavior of this to a tab (or several)? That would make it easy to listen to music from one tab and watch videos on others without having to toggle the button all the time.

**Comment by sheddup** [comment]
I will look into adding this. 
Can I ask, in what way would you select the tab you want to use for music only?

**Comment by Madis0** [comment]
I've thought about the UX of this for a while, and here's what I came up with:

- The button will show a popup with two options - toggle globally and toggle for this tab
- Global indication will be displayed like now with the change of the icon, tab exception will be displayed with the change of the icon and a badge "T"
- For better integration, a tab context menu item could be added "Mute video for this tab"
- Again, for better integration and overview: all video-muted tabs (whether globally or exceptions) should append a headphones emoji to the start of the title 🎧

**Comment by sheddup** [comment]
Right now I'm thinking this, two modes of operation: 

1. The default setting where you toggle it off/on globally by clicking the icon
2. Per tab setting where you toggle it only in the tabs you have clicked the icon

You would change the mode of operation in an options pane, not sure where that will be placed just yet though.

This is all theory as I've yet to write any code but it sounds entirely doable 👍

**Comment by sheddup** [comment]
[unzip-me.zip](https://github.com/sheddup/YoutubeAUDIO/files/1308860/unzip-me.zip)
@Madis0 So I've got an early version of the per-tab setting, can you test this by loading it as a temporary add-on. Note this version does not have the global toggle built in, just per tab setting purely for testing purposes.

If you don't know how to load a temp add-on do this, open **about:debugging** then click load temporary add-on then load the file '**load-me-as-temporary-addon.xpi**' _(this file is inside unzip-me.zip)_
![](https://user-images.githubusercontent.com/5480335/30518396-326b7baa-9b53-11e7-8a4e-c2942e2c4671.png)

**Comment by Madis0** [comment]
Seems to work well so far - tested with a single video, playlist and YouTube TV.

**Comment by sheddup** [comment]
Just need to polish a few things off and I should have the add-on updated within a day or two.

**Comment by sheddup** [comment]
The update is live, let me know of any issues.

**Comment by Madis0** [comment]
Oh yeah, one thing I forgot to ask - would it be possible to keep the tab's state between sessions?

**Comment by sheddup** [comment]
I guess its possible but I don't know anything about the session APIs yet haha 😂

**Comment by sheddup** [comment]
@Madis0 do you use Firefox 57 because the API to make this feature is only available in 57 so far

**Comment by Madis0** [comment]
Yes, I use 57.0b2 (Developer Edition).
