### ISSUE TITLE
Add option to disable thumbnail

### ISSUE THREAD

**Issue by draconk** [sheddup/YoutubeAUDIO#7]
When I use this addon is on work just to listen to some music or a podcast but sometimes the thumbnail for the video is not appropriate for work at all and since I have to open the tab to change the song I have to do it sneaky so nobody sees something NSFW it would be nice to just put a black image over the video or darken it (or just disable the video/thumbnail and just have the controls)

**Comment by sheddup** [comment]
Roger that, I'll add this soon.

**Comment by sheddup** [comment]
Check the update

**Comment by draconk** [comment]
Works like a charm! thanks a lot (and holy hell you are quick :smile:)
