### ISSUE TITLE
Can't hear sound anymore

### ISSUE THREAD

**Issue by Madis0** [sheddup/YoutubeAUDIO#8]
I can no longer hear any sound when YoutubeAUDIO is enabled. Perhaps a YouTube update? Firefox DevEd 58.0b11.

**Comment by sheddup** [comment]
I'm not seeing this behaviour, does this happen for every video? If its only some videos can you link an example?

**Comment by Madis0** [comment]
For every video, yes. Also tried a [competitor's extension](https://addons.mozilla.org/en-US/firefox/addon/youtube-audio/) which had the same result.

However, I tried with a clean profile where it worked, so it might be one of my about:config preferences.

Console log had written this:
`The HTMLMediaElement passed to createMediaElementSource has a cross-origin resource, the node will output silence.`

**Comment by Madis0** [comment]
Yes, it happens for every video. Tried on a clean profile where it didn't occur though, so it might be one of my extensions/about:config settings 😁 

The console log had written this: `The HTMLMediaElement passed to createMediaElementSource has a cross-origin resource, the node will output silence.`

**Comment by sheddup** [comment]
Yes it could be a conflict with other addons, what other addons do you use that interact with youtube?  
You could selectively enable your extensions one by one until youtubeAUDIO breaks to help identify the conflict.

**Comment by Madis0** [comment]
Heh, it was actually simpler than I thought. I was using [this Chrome extension](https://chrome.google.com/webstore/detail/karaoke-mode-for-youtube/ghnaglacgepiijbbkpfdoncgfadgkdck?hl=en-GB) which could previously co-exist with this well, but apparently something changed. Then again that one hasn't been updated for years so it is not too surprising.

**Comment by sheddup** [comment]
Ok I just reproduced the silence, I don't think I can fix this but I'll look into it anyway.

**Comment by Madis0** [comment]
Perhaps you could instead implement a similar karaoke filter feature into this extension? From the source it seems to be just local JS/jquery. 

The lyrics feature isn't necessary.

**Comment by sheddup** [comment]
Changing the crossOrigin attribute on youtube's video element seems to have fixed the problem, I haven't tested many videos so I hope this fix doesn't break anything in the process.
Can you please test the fix for me? (load the attachment as a temporary extension)
[corsfix.zip](https://github.com/sheddup/YoutubeAUDIO/files/1564567/corsfix.zip)

**Comment by Madis0** [comment]
The fix seems to work for me too.

**Comment by sheddup** [comment]
I've updated the extension if it breaks again let me know
